apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbookreadprofile-deployment
  labels:
    app: blackbookreadprofile
spec:
  selector:
    matchLabels:
      app: blackbookreadprofile
  template:
    metadata:
      labels:
        app: blackbookreadprofile
    spec:
      containers:
      - name: blackbookreadprofile
        image: docker.io/rlkamradt/blackbook-read-profile:latest
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: username
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password
          - name: MONGO_SERVER
            value: mongodb-0.mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: blackbookreadprofile-service
spec:
  type: ClusterIP
  selector:
    app: blackbookreadprofile
  ports:
  - port: 8080
    targetPort: 3000
