apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: blackbook-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: blackbook.kamradtfamily.net
    http:
      paths:
      - backend:
          serviceName: blackbook-service
          servicePort: 8080
        path: /
  - host: blackbookreadprofile.kamradtfamily.net
    http:
      paths:
      - backend:
          serviceName: blackbookreadprofile-service
          servicePort: 3000
        path: /
  tls:
  - hosts:
    - blackbook.kamradtfamily.net
      secretName: kamradtfamily
    - blackbookreadprofile.kamradtfamily.net
      secretName: kamradtfamily
